version: '3.9'

services:

  fastapi:
    build: .
    volumes:
      - .:/app
    command: /bin/sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - celery_beat

  celery_worker:
    build: .
    volumes:
      - .:/app
    command: celery -A celeryconfig worker --loglevel=info
    depends_on:
      - redis
      - rabbitmq
      - db

  celery_beat:
    build: .
    volumes:
      - .:/app
    command: celery -A celeryconfig  beat --loglevel=info
    depends_on:
      - celery_worker

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  db:
    image: 'postgres:13.0-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:

