"""initial

Revision ID: b8f5f74e0fac
Revises: 
Create Date: 2023-10-04 12:35:27.468558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f5f74e0fac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('proxy_address', sa.String(length=50), nullable=True),
    sa.Column('port', sa.String(length=10), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('last_verification', sa.String(length=60), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city_name', sa.String(length=60), nullable=True),
    sa.Column('asn_name', sa.String(length=75), nullable=True),
    sa.Column('asn_number', sa.Integer(), nullable=True),
    sa.Column('high_country_confidence', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proxies')
    # ### end Alembic commands ###
